'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace SuperTRUMPAllDealService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://www.garimasikarwar.com", ConfigurationName:="SuperTRUMPAllDealService.ISuperTRUMPAllDealService")>  _
    Public Interface ISuperTRUMPAllDealService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.garimasikarwar.com/ISuperTRUMPAllDealService/TestSuperTRUMPAllDealServ"& _ 
            "ice", ReplyAction:="http://www.garimasikarwar.com/ISuperTRUMPAllDealService/TestSuperTRUMPAllDealServ"& _ 
            "iceResponse")>  _
        Function TestSuperTRUMPAllDealService(ByVal myValue As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.garimasikarwar.com/ISuperTRUMPAllDealService/LoadDWData", ReplyAction:="http://www.garimasikarwar.com/ISuperTRUMPAllDealService/LoadDWDataResponse")>  _
        Function LoadDWData() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.garimasikarwar.com/ISuperTRUMPAllDealService/GenerateInputXML", ReplyAction:="http://www.garimasikarwar.com/ISuperTRUMPAllDealService/GenerateInputXMLResponse")>  _
        Function GenerateInputXML() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://www.garimasikarwar.com/ISuperTRUMPAllDealService/ExecuteServiceFlow", ReplyAction:="http://www.garimasikarwar.com/ISuperTRUMPAllDealService/ExecuteServiceFlowRespons"& _ 
            "e")>  _
        Function ExecuteServiceFlow() As String
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ISuperTRUMPAllDealServiceChannel
        Inherits SuperTRUMPAllDealService.ISuperTRUMPAllDealService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class SuperTRUMPAllDealServiceClient
        Inherits System.ServiceModel.ClientBase(Of SuperTRUMPAllDealService.ISuperTRUMPAllDealService)
        Implements SuperTRUMPAllDealService.ISuperTRUMPAllDealService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function TestSuperTRUMPAllDealService(ByVal myValue As String) As String Implements SuperTRUMPAllDealService.ISuperTRUMPAllDealService.TestSuperTRUMPAllDealService
            Return MyBase.Channel.TestSuperTRUMPAllDealService(myValue)
        End Function
        
        Public Function LoadDWData() As String Implements SuperTRUMPAllDealService.ISuperTRUMPAllDealService.LoadDWData
            Return MyBase.Channel.LoadDWData
        End Function
        
        Public Function GenerateInputXML() As String Implements SuperTRUMPAllDealService.ISuperTRUMPAllDealService.GenerateInputXML
            Return MyBase.Channel.GenerateInputXML
        End Function
        
        Public Function ExecuteServiceFlow() As String Implements SuperTRUMPAllDealService.ISuperTRUMPAllDealService.ExecuteServiceFlow
            Return MyBase.Channel.ExecuteServiceFlow
        End Function
    End Class
End Namespace
