//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4984.
// 
#pragma warning disable 1591

namespace ISTWebSrvService.BSCEFSuperTrump {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IClientServiceSoapPort", Namespace="http://tempuri.org/")]
    public partial class IClientServiceSoapPort : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessMQMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessPricingRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IClientServiceSoapPort() {
            this.Url = "http://soacluster1.dev.comfin.ge.com/BSCEFSuperTrumpNet/SupertrumpService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event ProcessMQMessageCompletedEventHandler ProcessMQMessageCompleted;
        
        /// <remarks/>
        public event ProcessPricingRequestCompletedEventHandler ProcessPricingRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ping", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessMQMessage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcessMQMessage(string astrMQMsgInfoXML) {
            object[] results = this.Invoke("ProcessMQMessage", new object[] {
                        astrMQMsgInfoXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessMQMessageAsync(string astrMQMsgInfoXML) {
            this.ProcessMQMessageAsync(astrMQMsgInfoXML, null);
        }
        
        /// <remarks/>
        public void ProcessMQMessageAsync(string astrMQMsgInfoXML, object userState) {
            if ((this.ProcessMQMessageOperationCompleted == null)) {
                this.ProcessMQMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessMQMessageOperationCompleted);
            }
            this.InvokeAsync("ProcessMQMessage", new object[] {
                        astrMQMsgInfoXML}, this.ProcessMQMessageOperationCompleted, userState);
        }
        
        private void OnProcessMQMessageOperationCompleted(object arg) {
            if ((this.ProcessMQMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessMQMessageCompleted(this, new ProcessMQMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessPricingRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProcessPricingRequest(string astrPricingRequestXML) {
            object[] results = this.Invoke("ProcessPricingRequest", new object[] {
                        astrPricingRequestXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessPricingRequestAsync(string astrPricingRequestXML) {
            this.ProcessPricingRequestAsync(astrPricingRequestXML, null);
        }
        
        /// <remarks/>
        public void ProcessPricingRequestAsync(string astrPricingRequestXML, object userState) {
            if ((this.ProcessPricingRequestOperationCompleted == null)) {
                this.ProcessPricingRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessPricingRequestOperationCompleted);
            }
            this.InvokeAsync("ProcessPricingRequest", new object[] {
                        astrPricingRequestXML}, this.ProcessPricingRequestOperationCompleted, userState);
        }
        
        private void OnProcessPricingRequestOperationCompleted(object arg) {
            if ((this.ProcessPricingRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessPricingRequestCompleted(this, new ProcessPricingRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ISuperTrumpServiceSoapPort", Namespace="http://tempuri.org/")]
    public partial class ISuperTrumpServiceSoapPort : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConvertPRMToXMLOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePRMFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAmortizationScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPricingReportsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPRMParamsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModifyPRMFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestOperationCompleted;
        
        private System.Threading.SendOrPostCallback RunAdHocXMLInOutQueryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePRMFilesForPmtStructOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePRMFilesForPmtStruct2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ISuperTrumpServiceSoapPort() {
            this.Url = "http://soacluster1.dev.comfin.ge.com/BSCEFSuperTrumpNet/SupertrumpService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConvertPRMToXMLCompletedEventHandler ConvertPRMToXMLCompleted;
        
        /// <remarks/>
        public event GeneratePRMFilesCompletedEventHandler GeneratePRMFilesCompleted;
        
        /// <remarks/>
        public event GetAmortizationScheduleCompletedEventHandler GetAmortizationScheduleCompleted;
        
        /// <remarks/>
        public event GetPricingReportsCompletedEventHandler GetPricingReportsCompleted;
        
        /// <remarks/>
        public event GetPRMParamsCompletedEventHandler GetPRMParamsCompleted;
        
        /// <remarks/>
        public event ModifyPRMFilesCompletedEventHandler ModifyPRMFilesCompleted;
        
        /// <remarks/>
        public event TestCompletedEventHandler TestCompleted;
        
        /// <remarks/>
        public event RunAdHocXMLInOutQueryCompletedEventHandler RunAdHocXMLInOutQueryCompleted;
        
        /// <remarks/>
        public event GeneratePRMFilesForPmtStructCompletedEventHandler GeneratePRMFilesForPmtStructCompleted;
        
        /// <remarks/>
        public event GeneratePRMFilesForPmtStruct2CompletedEventHandler GeneratePRMFilesForPmtStruct2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConvertPRMToXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConvertPRMToXML(string astrPRMFileListXML) {
            object[] results = this.Invoke("ConvertPRMToXML", new object[] {
                        astrPRMFileListXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConvertPRMToXMLAsync(string astrPRMFileListXML) {
            this.ConvertPRMToXMLAsync(astrPRMFileListXML, null);
        }
        
        /// <remarks/>
        public void ConvertPRMToXMLAsync(string astrPRMFileListXML, object userState) {
            if ((this.ConvertPRMToXMLOperationCompleted == null)) {
                this.ConvertPRMToXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertPRMToXMLOperationCompleted);
            }
            this.InvokeAsync("ConvertPRMToXML", new object[] {
                        astrPRMFileListXML}, this.ConvertPRMToXMLOperationCompleted, userState);
        }
        
        private void OnConvertPRMToXMLOperationCompleted(object arg) {
            if ((this.ConvertPRMToXMLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertPRMToXMLCompleted(this, new ConvertPRMToXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneratePRMFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GeneratePRMFiles(string astrPRMInfoXML) {
            object[] results = this.Invoke("GeneratePRMFiles", new object[] {
                        astrPRMInfoXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GeneratePRMFilesAsync(string astrPRMInfoXML) {
            this.GeneratePRMFilesAsync(astrPRMInfoXML, null);
        }
        
        /// <remarks/>
        public void GeneratePRMFilesAsync(string astrPRMInfoXML, object userState) {
            if ((this.GeneratePRMFilesOperationCompleted == null)) {
                this.GeneratePRMFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePRMFilesOperationCompleted);
            }
            this.InvokeAsync("GeneratePRMFiles", new object[] {
                        astrPRMInfoXML}, this.GeneratePRMFilesOperationCompleted, userState);
        }
        
        private void OnGeneratePRMFilesOperationCompleted(object arg) {
            if ((this.GeneratePRMFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePRMFilesCompleted(this, new GeneratePRMFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAmortizationSchedule", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAmortizationSchedule(string astrPRMFileListXML) {
            object[] results = this.Invoke("GetAmortizationSchedule", new object[] {
                        astrPRMFileListXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAmortizationScheduleAsync(string astrPRMFileListXML) {
            this.GetAmortizationScheduleAsync(astrPRMFileListXML, null);
        }
        
        /// <remarks/>
        public void GetAmortizationScheduleAsync(string astrPRMFileListXML, object userState) {
            if ((this.GetAmortizationScheduleOperationCompleted == null)) {
                this.GetAmortizationScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAmortizationScheduleOperationCompleted);
            }
            this.InvokeAsync("GetAmortizationSchedule", new object[] {
                        astrPRMFileListXML}, this.GetAmortizationScheduleOperationCompleted, userState);
        }
        
        private void OnGetAmortizationScheduleOperationCompleted(object arg) {
            if ((this.GetAmortizationScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAmortizationScheduleCompleted(this, new GetAmortizationScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPricingReports", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPricingReports(string astrPricingRepInfoXML) {
            object[] results = this.Invoke("GetPricingReports", new object[] {
                        astrPricingRepInfoXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPricingReportsAsync(string astrPricingRepInfoXML) {
            this.GetPricingReportsAsync(astrPricingRepInfoXML, null);
        }
        
        /// <remarks/>
        public void GetPricingReportsAsync(string astrPricingRepInfoXML, object userState) {
            if ((this.GetPricingReportsOperationCompleted == null)) {
                this.GetPricingReportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPricingReportsOperationCompleted);
            }
            this.InvokeAsync("GetPricingReports", new object[] {
                        astrPricingRepInfoXML}, this.GetPricingReportsOperationCompleted, userState);
        }
        
        private void OnGetPricingReportsOperationCompleted(object arg) {
            if ((this.GetPricingReportsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPricingReportsCompleted(this, new GetPricingReportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPRMParams", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPRMParams(string astrPRMParamsInfoXML) {
            object[] results = this.Invoke("GetPRMParams", new object[] {
                        astrPRMParamsInfoXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPRMParamsAsync(string astrPRMParamsInfoXML) {
            this.GetPRMParamsAsync(astrPRMParamsInfoXML, null);
        }
        
        /// <remarks/>
        public void GetPRMParamsAsync(string astrPRMParamsInfoXML, object userState) {
            if ((this.GetPRMParamsOperationCompleted == null)) {
                this.GetPRMParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPRMParamsOperationCompleted);
            }
            this.InvokeAsync("GetPRMParams", new object[] {
                        astrPRMParamsInfoXML}, this.GetPRMParamsOperationCompleted, userState);
        }
        
        private void OnGetPRMParamsOperationCompleted(object arg) {
            if ((this.GetPRMParamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPRMParamsCompleted(this, new GetPRMParamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModifyPRMFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ModifyPRMFiles(string astrModifyPRMFilesXML) {
            object[] results = this.Invoke("ModifyPRMFiles", new object[] {
                        astrModifyPRMFilesXML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ModifyPRMFilesAsync(string astrModifyPRMFilesXML) {
            this.ModifyPRMFilesAsync(astrModifyPRMFilesXML, null);
        }
        
        /// <remarks/>
        public void ModifyPRMFilesAsync(string astrModifyPRMFilesXML, object userState) {
            if ((this.ModifyPRMFilesOperationCompleted == null)) {
                this.ModifyPRMFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModifyPRMFilesOperationCompleted);
            }
            this.InvokeAsync("ModifyPRMFiles", new object[] {
                        astrModifyPRMFilesXML}, this.ModifyPRMFilesOperationCompleted, userState);
        }
        
        private void OnModifyPRMFilesOperationCompleted(object arg) {
            if ((this.ModifyPRMFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModifyPRMFilesCompleted(this, new ModifyPRMFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Test", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Test() {
            object[] results = this.Invoke("Test", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestAsync() {
            this.TestAsync(null);
        }
        
        /// <remarks/>
        public void TestAsync(object userState) {
            if ((this.TestOperationCompleted == null)) {
                this.TestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestOperationCompleted);
            }
            this.InvokeAsync("Test", new object[0], this.TestOperationCompleted, userState);
        }
        
        private void OnTestOperationCompleted(object arg) {
            if ((this.TestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestCompleted(this, new TestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunAdHocXMLInOutQuery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RunAdHocXMLInOutQuery(string astrXMLInOutQuery) {
            object[] results = this.Invoke("RunAdHocXMLInOutQuery", new object[] {
                        astrXMLInOutQuery});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RunAdHocXMLInOutQueryAsync(string astrXMLInOutQuery) {
            this.RunAdHocXMLInOutQueryAsync(astrXMLInOutQuery, null);
        }
        
        /// <remarks/>
        public void RunAdHocXMLInOutQueryAsync(string astrXMLInOutQuery, object userState) {
            if ((this.RunAdHocXMLInOutQueryOperationCompleted == null)) {
                this.RunAdHocXMLInOutQueryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunAdHocXMLInOutQueryOperationCompleted);
            }
            this.InvokeAsync("RunAdHocXMLInOutQuery", new object[] {
                        astrXMLInOutQuery}, this.RunAdHocXMLInOutQueryOperationCompleted, userState);
        }
        
        private void OnRunAdHocXMLInOutQueryOperationCompleted(object arg) {
            if ((this.RunAdHocXMLInOutQueryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunAdHocXMLInOutQueryCompleted(this, new RunAdHocXMLInOutQueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneratePRMFilesForPmtStruct", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GeneratePRMFilesForPmtStruct(string astrXMLInOutQuery) {
            object[] results = this.Invoke("GeneratePRMFilesForPmtStruct", new object[] {
                        astrXMLInOutQuery});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GeneratePRMFilesForPmtStructAsync(string astrXMLInOutQuery) {
            this.GeneratePRMFilesForPmtStructAsync(astrXMLInOutQuery, null);
        }
        
        /// <remarks/>
        public void GeneratePRMFilesForPmtStructAsync(string astrXMLInOutQuery, object userState) {
            if ((this.GeneratePRMFilesForPmtStructOperationCompleted == null)) {
                this.GeneratePRMFilesForPmtStructOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePRMFilesForPmtStructOperationCompleted);
            }
            this.InvokeAsync("GeneratePRMFilesForPmtStruct", new object[] {
                        astrXMLInOutQuery}, this.GeneratePRMFilesForPmtStructOperationCompleted, userState);
        }
        
        private void OnGeneratePRMFilesForPmtStructOperationCompleted(object arg) {
            if ((this.GeneratePRMFilesForPmtStructCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePRMFilesForPmtStructCompleted(this, new GeneratePRMFilesForPmtStructCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneratePRMFilesForPmtStruct2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GeneratePRMFilesForPmtStruct2(string astrXMLInOutQuery) {
            object[] results = this.Invoke("GeneratePRMFilesForPmtStruct2", new object[] {
                        astrXMLInOutQuery});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GeneratePRMFilesForPmtStruct2Async(string astrXMLInOutQuery) {
            this.GeneratePRMFilesForPmtStruct2Async(astrXMLInOutQuery, null);
        }
        
        /// <remarks/>
        public void GeneratePRMFilesForPmtStruct2Async(string astrXMLInOutQuery, object userState) {
            if ((this.GeneratePRMFilesForPmtStruct2OperationCompleted == null)) {
                this.GeneratePRMFilesForPmtStruct2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePRMFilesForPmtStruct2OperationCompleted);
            }
            this.InvokeAsync("GeneratePRMFilesForPmtStruct2", new object[] {
                        astrXMLInOutQuery}, this.GeneratePRMFilesForPmtStruct2OperationCompleted, userState);
        }
        
        private void OnGeneratePRMFilesForPmtStruct2OperationCompleted(object arg) {
            if ((this.GeneratePRMFilesForPmtStruct2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePRMFilesForPmtStruct2Completed(this, new GeneratePRMFilesForPmtStruct2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ProcessMQMessageCompletedEventHandler(object sender, ProcessMQMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessMQMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessMQMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ProcessPricingRequestCompletedEventHandler(object sender, ProcessPricingRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessPricingRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessPricingRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ConvertPRMToXMLCompletedEventHandler(object sender, ConvertPRMToXMLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertPRMToXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertPRMToXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GeneratePRMFilesCompletedEventHandler(object sender, GeneratePRMFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneratePRMFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneratePRMFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetAmortizationScheduleCompletedEventHandler(object sender, GetAmortizationScheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAmortizationScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAmortizationScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetPricingReportsCompletedEventHandler(object sender, GetPricingReportsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPricingReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPricingReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GetPRMParamsCompletedEventHandler(object sender, GetPRMParamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPRMParamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPRMParamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ModifyPRMFilesCompletedEventHandler(object sender, ModifyPRMFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModifyPRMFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModifyPRMFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void TestCompletedEventHandler(object sender, TestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RunAdHocXMLInOutQueryCompletedEventHandler(object sender, RunAdHocXMLInOutQueryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunAdHocXMLInOutQueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RunAdHocXMLInOutQueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GeneratePRMFilesForPmtStructCompletedEventHandler(object sender, GeneratePRMFilesForPmtStructCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneratePRMFilesForPmtStructCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneratePRMFilesForPmtStructCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void GeneratePRMFilesForPmtStruct2CompletedEventHandler(object sender, GeneratePRMFilesForPmtStruct2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneratePRMFilesForPmtStruct2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneratePRMFilesForPmtStruct2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591