
CREATE TABLE VIC_ROI.TBL_PRM_PROCESS
(
  PRMID                NUMBER                   NOT NULL,
  PRMTRANSACTIONSTATE  VARCHAR2(4000 BYTE),
  INPUTXML             VARCHAR2(4000 BYTE),
  DATEUPDATE           DATE,
  PROCESSDATE          DATE,
  FOLDERPATH           VARCHAR2(1000 BYTE)
)
TABLESPACE VIC_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;




